### ISSUE TITLE
Import Aton

### ISSUE THREAD

**Issue by eschulist** [Sosoyan/Aton#13]
I've placed the aton.dylib file in probably 10 different locations in the Nuke directory, plugin folder, .nuke folder, and our network plugin/scripts folders and every time I call Import Aton inside the init file it say that module does not exist.  Where is it suppose to go?

The same for the Maya location inside Arnold.  It is inside Arnold's SolidAngle folder in a couple different places and each time I run
from aton_maya import *
aton = Aton()
aton.show()

It says no module is named aton_maya.

Thanks

**Comment by sosoyan** [comment]
It's pretty straight forward, check here http://sosoyan.github.io/Aton/ 

Make sure in your init.py you have only this line bellow to load it

## nuke.load("aton")

Regarding to maya make sure to copy aton_maya.py from ~/Scripts to your Maya's scripts folder

Let me know if it still not working for you.

**Comment by eschulist** [comment]
OK the readme had "Import Aton" in the init file before.
The maya py was just aton.py not aton_maya.py  Thank you for updating it.  

It is now loading both but I get another error in Nuke.

Symbol not found: _fchmodat
  Referenced from: /Volumes/3D/NUKE/aton.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Volumes/3D/NUKE/aton.dylib

That seems to be an operating system error.  Im using 10.9.5

**Comment by sosoyan** [comment]
It's strange, my deployment target is set to 10.6 however I'm running on 10.11. You can try to build it yourself if you think it's still an OS issue.

Thanks.
