### ISSUE TITLE
Maya Script

### ISSUE THREAD

**Issue by harratus** [Sosoyan/Aton#14]
I'm having troubles installing the aton_maya script. I tried every Script folder that Maya offers but when i try to load the script in Maya I get the error

// Error: Line 1.23: Syntax error

**Comment by sosoyan** [comment]
Make sure you are running this as a PYTHON script, not MEL

from aton_maya import *
aton = Aton()
aton.show()

**Comment by harratus** [comment]
Thank you! Works like a charm now :)
