### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by Frecnhfeeling** [Sosoyan/Aton#16]
I've tried to instale your plug-in, following the steps but didnt work in Nuke. 

The script editor in Maya return numbers lines so i think it's working in Maya (the panel is here and action in script editor too). 
But nothing append in Nuke with the node Aton.

I've verified my version of Nuke and Arnold and they are correct too. 

Any suggestions ?

**Comment by sosoyan** [comment]
on which platform are you running?

**Comment by Frecnhfeeling** [comment]
Windows 7

**Comment by sosoyan** [comment]
I presume you are creating Aton node in nuke before starting the render right?

Do you have "aton" in drivers list in Maya > Render Settings > AOVs > Default Drivers ?

**Comment by Frecnhfeeling** [comment]
Yes i created Aton node before starting render. 

No, i dont have aton in AOVs. 
But i checked my path for the aton driver and it's seen correct : C:\solidangle\mtoadeploy\2015\shaders

My version of Maya is 2015.

**Comment by sosoyan** [comment]
Can you double check if you haven't this in your drivers drop down list?https://dl.dropboxusercontent.com/u/11663164/aton_render_settings.png

**Comment by Frecnhfeeling** [comment]
I checked again and i am sure i havent but i found this when maya loaded : 

00:00:00   495MB WARNING |  driver_aton.dll was compiled against non-compatible Arnold 4.2.8.0

00:00:00 WARNING |  driver_aton.dll was compiled against non-compatible Arnold 4.2.8.0

**Comment by sosoyan** [comment]
That's make sense, can you update your arnold version? 
Which version are you using and do you have a reason to avoid updating?
