### ISSUE TITLE
Problem with Dependencies  in the driver_aton.dylib

### ISSUE THREAD

**Issue by sxandy** [Sosoyan/Aton#18]
Hallo
in the Arnold log I get this error

00:00:01 WARNING |  unable to load dynamic library: dlopen(/solidangle/extraShader/bin//driver_aton.dylib, 5): Library not loaded: /usr/local/opt/boost/lib/libboost_atomic-mt.dylib
  Referenced from: /solidangle/extraShader/bin//driver_aton.dylib
  Reason: image not found

and there are a lot more dependencies to other libboost dylibs.
I think this is not right, or are they needed ?

**Comment by sosoyan** [comment]
You don't need boost to just load it, all dependancies are included in itself. Just put driver_aton.dylib in the Arnold's shaders directory, and it should load it.

Let me know if it still fails.

**Comment by sosoyan** [comment]
I've just double checked and found the issue, if you re download the driver_aton.dylib it should be fine now!

**Comment by sxandy** [comment]
Yes now it works and thank you for this i think this is really useful.
Have a nice day.

**Comment by sosoyan** [comment]
Thanks for reporting.
