### ISSUE TITLE
Using Aton over local network

### ISSUE THREAD

**Issue by silpatel92** [Sosoyan/Aton#51]
Hey,

I am compositor and I am amazed with this plugin. First of all I want to thank you guys creating this plugin. This is certainly taking the VFX workflow pipeline to a new level. 
For now I have it work flawlessly on my machine but was wondering if it is possible to have it work between two or more machines over the local network ?

Really appreciate your help !!!

Thank you,
Sheel

**Comment by sosoyan** [comment]
Hi,

First sorry for the late reply. Yes you certainly can use it over the local network. Have you tried to insert the machine's IP in the Host that you want to stream to?

<img width="484" alt="screen shot 2018-05-01 at 08 56 35" src="https://user-images.githubusercontent.com/5727306/39461693-99dcc83a-4d1d-11e8-84c0-a28633d5151b.png">

Thanks.

**Comment by silpatel92** [comment]
Hey !!

Thank you so much for your help. I got it working. It is amazing!!!!!
