### ISSUE TITLE
Prevent extra empty formats from being initiated in nuke

### ISSUE THREAD

**Issue by bscherbi** [Sosoyan/Aton#6]
Right now since the format is made on node initialisation it creates a new format for every time a node is created. We should have a scene wide flag to see if the "renderConnect" format is already there and not make new ones if so.

**Comment by bscherbi** [comment]
fixed with commit:
https://github.com/Sosoyan/renderconnect/commit/d5c74901a1a6a27085283707d596d0e8f64af733

**Comment by bscherbi** [comment]
When creating the renderconnect node it gives a popup windows with true or false if it exists already.
This should not pop up

**Comment by sosoyan** [comment]
I didn't get it, which popup?
