### ISSUE TITLE
Trying to build from source, crashes both Maya and Nuke

### ISSUE THREAD

**Issue by melMass** [Sosoyan/Aton#65]
Hello,

I'm trying to build the current master and tag 1.2.2 but both crashes Nuke, then Maya.
Running both from the command line but no relevant output there. Can you help me provide more useful information ? 

Built with:
OSX Sierra 10.12.6
Nuke 11.0v1 & 11.2v1
Arnold 5.2.0
mtoa 3.1.0 (Ai 5.2 Core)
Boost version: 1.67.0

Thanks

**Comment by sosoyan** [comment]
Hi, can you try to load these and see if it works?

[aton-1.3.0b_nuke-11.2_arnold-5.2.zip](https://github.com/Sosoyan/Aton/files/2371535/aton-1.3.0b_nuke-11.2_arnold-5.2.zip)

**Comment by melMass** [comment]
Works like a charm!!

Would you mind sharing how you built it ?

**Comment by sosoyan** [comment]
Are you building with cmake or xcode?

**Comment by melMass** [comment]
Using CMake.

**Comment by sosoyan** [comment]
I would try to link against boost 1.54 or 1.58, that's what I'm using.

Cheers.
