### ISSUE TITLE
How to autosave snapshots ?

### ISSUE THREAD

**Issue by melMass** [Sosoyan/Aton#66]
Can you quickly explain how the new sequence/ write multi frames work ?
And also is there a way to autosave snapshots ?

Thanks

**Comment by sosoyan** [comment]
When you are in Multiple Frames Mode (which means new frames are being stored on the timeline of the current snapshot rather than in new snapshot), checking Write Multiple Frames will render the whole sequence of the selected snapshot instead of a single frame.
