### ISSUE TITLE
HtoA Houdini IPR Update Bug

### ISSUE THREAD

**Issue by adrianmeyerart** [Sosoyan/Aton#68]
Hi,
when I use Aton with Houdini the IPR Update in Houdini itself does not get updated.
I image gets updated in Nuke correctly but the IPR in Houdini says "Generating Scene" and stays black after having started it over the Aton UI.
Would be very nice to have the updated renderbuffer in both Apps!
Is this a bug or am I missing something?

Thanks!

Win 10
Aton 1.3.5
Houdini 17.5.293
htoa-4.1.1_rf2c4e45_houdini-17.5.293
Arnold 5.3.1.1

**Comment by sosoyan** [comment]
Hi Adrien,

Sorry for late reply, it is expected as the output drivers are being changed to driver_aton. It would affect the performance if we just double them up, however it is easy enough to add it if you want to. 

Add "+ outputs" at the end of the following line.

`aton_outputs = [i.replace(driver_name, aton_name) for i in outputs if "variance_filter" not in i] + outputs`

https://github.com/Sosoyan/Aton/blob/master/scripts/aton_houdini.py#L107

Cheers.

**Comment by adrianmeyerart** [comment]
Hi,
Thanks a lot!
Could you roughly tell me what kind of performance impact this would have?
It will not actually render twice I guess?
Just output the renderbuffer two times right? So I would suppose the cost wouldn’t be to high?

Thanks again.

**Comment by sosoyan** [comment]
Yes it will affect mostly the first IPR iterations as usually they are running fast.

**Comment by adrianmeyerart** [comment]
Thanks,
worked like a charm
