### ISSUE TITLE
Update Houdini install instructions

### ISSUE THREAD

**Issue by mruegenberg** [Sosoyan/Aton#70]
The install instructions state to add the patch after line 71 of `arnold.py`. However, there seems to have been an update to HtoA (in my case htoa-5.5.0.1, matching Arnold 6.1) which removed a lot of code, so `arnold.py` only contains about 14 lines. 

From comparing with an old HtoA 4.0 I had lying around I believe the instructions should be changed to line 5 (and more generally just before `getSession.run()` is called.

**Comment by sosoyan** [comment]
Thanks, that is correct, I've just updated the instructions.
